url: https://caositu.github.io
baseurl: /

 
keywords: "Cao Siyao"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "assets/img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown","package.json", "src", "node_modules"]
# Site settings
title: Cao Siyao
description: A Personal webiste of AndyTaoLi
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
## particle setting： https://blog.csdn.net/csdn_yudong/article/details/53128570
# User settings
username: Cao Siyao
user_description: Master at Tsinghua SEM
user_title: Risk Manager at Ping An Insurance
email: andytaolee@gmail.com
twitter_username: andytaoli
github_username:  andytaoli
gplus_username:  andytaoli
#cv_address:  "assets/cv/caosiyao.pdf"
cv_address:  "#"
