url: https://andytaoli.github.io
baseurl: /

 
keywords: "jekyll, theme"
google-tracking-id:

# Career Settings
# Default career thumbnail image.
career-img: "img/timeline/default.jpg"

exclude: ["Rakefile", "LICENSE", "readme.markdown"，'package.json', 'src' , 'node_modules']
# Site settings
title: AndyTaoLi
description: A Personal webiste of AndyTaoLi
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
## particle setting： https://blog.csdn.net/csdn_yudong/article/details/53128570
# User settings
username: Andy Tao Li
user_description: Ph.D Candidate at Tsinghua SEM
user_title: Ph.D Candidate at Tsinghua
email: andytaolee@gmail.com
twitter_username: andytaoli
github_username:  andytaoli
gplus_username:  andytaoli

# Google-analytics
google-analytics:
  id: ""

 