# Site settings
title: AndyTaoLi
description: A Personal webiste of AndyTaoLi
# baseurl: "/particle" # the subpath of your site, e.g. /blog
# url: "localhost:3000" # the base hostname & protocol for your site e.g. http://willianjusten.com.br
## particle setting： https://blog.csdn.net/csdn_yudong/article/details/53128570
# User settings
username: Andy Tao Li
user_description: A Ph.D Candidate at School of Economics and Management, Tsinghua University
user_title: Ph.D Candidate at Tsinghua University
email: andytaolee@gmail.com
twitter_username: andytaoli
github_username:  andytaoli
gplus_username:  andytaoli

# Google-analytics
google-analytics:
  id: ""

exclude: ['package.json', 'src' , 'node_modules']
